Repository goodmn79/backend-react-avito, pull requests merged in 2025-03, with the labels that each got.

#79 Feature/javadoc
  pom.xml
  src/main/java/ru/skypro/homework/component/mapper/AdMapper.java
  src/main/java/ru/skypro/homework/component/mapper/CommentMapper.java
  src/main/java/ru/skypro/homework/component/mapper/UserMapper.java
  src/main/java/ru/skypro/homework/component/validation/DataValidator.java
  src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
  src/main/java/ru/skypro/homework/controller/AdController.java
  src/main/java/ru/skypro/homework/controller/AuthController.java
  src/main/java/ru/skypro/homework/controller/CommentController.java
  src/main/java/ru/skypro/homework/controller/UserController.java
  src/main/java/ru/skypro/homework/dto/ad/Ad.java
  src/main/java/ru/skypro/homework/dto/ad/Ads.java
  src/main/java/ru/skypro/homework/dto/ad/CreateOrUpdateAd.java
  src/main/java/ru/skypro/homework/dto/ad/ExtendedAd.java
  src/main/java/ru/skypro/homework/dto/comment/Comment.java
  src/main/java/ru/skypro/homework/dto/comment/Comments.java
  src/main/java/ru/skypro/homework/dto/comment/CreateOrUpdateComment.java
  src/main/java/ru/skypro/homework/dto/user/Login.java
  src/main/java/ru/skypro/homework/dto/user/NewPassword.java
  src/main/java/ru/skypro/homework/dto/user/Register.java
  src/main/java/ru/skypro/homework/dto/user/UpdateUser.java
  src/main/java/ru/skypro/homework/dto/user/User.java
  src/main/java/ru/skypro/homework/entity/AdEntity.java
  src/main/java/ru/skypro/homework/entity/CommentEntity.java
  src/main/java/ru/skypro/homework/entity/Image.java
  src/main/java/ru/skypro/homework/entity/UserEntity.java
  src/main/java/ru/skypro/homework/enums/ImageExtension.java
  src/main/java/ru/skypro/homework/enums/Role.java
  src/main/java/ru/skypro/homework/exception/AdNotFoundException.java
  src/main/java/ru/skypro/homework/exception/CommentNotFoundException.java
  src/main/java/ru/skypro/homework/exception/IllegalDataException.java
  src/main/java/ru/skypro/homework/exception/ImageNotFoundException.java
  src/main/java/ru/skypro/homework/exception/NoAccessRightException.java
  src/main/java/ru/skypro/homework/exception/PasswordDoesNotMatchException.java
  src/main/java/ru/skypro/homework/exception/UnsuccessfulImageSavingException.java
  src/main/java/ru/skypro/homework/exception/UserNotFoundException.java
  src/main/java/ru/skypro/homework/exception/WrongFileFormatException.java
  src/main/java/ru/skypro/homework/filter/BasicAuthCorsFilter.java
  src/main/java/ru/skypro/homework/repository/AdRepository.java
  src/main/java/ru/skypro/homework/repository/CommentRepository.java
  src/main/java/ru/skypro/homework/repository/ImageRepository.java
  src/main/java/ru/skypro/homework/repository/UserRepository.java
Labels: документация

#67 добавление конфигурации для связи бэка и фронта
  src/main/java/ru/skypro/homework/config/CorsConfig.java
  src/main/java/ru/skypro/homework/controller/AuthController.java
Labels: улучшение

#75 Hotfix/dip
  src/main/java/ru/skypro/homework/service/AdService.java
  src/main/java/ru/skypro/homework/service/CommentService.java
  src/main/java/ru/skypro/homework/service/ImageService.java
  src/main/java/ru/skypro/homework/service/UserService.java
  src/main/java/ru/skypro/homework/service/impl/AdServiceImpl.java
  src/main/java/ru/skypro/homework/service/impl/CommentServiceImpl.java
  src/main/java/ru/skypro/homework/service/impl/ImageServiceImpl.java
  src/main/java/ru/skypro/homework/service/impl/UserServiceImpl.java
Labels: исправление
