Repository goodmn79/backend-react-avito, pull requests merged in 2025-02, with the labels that each got.

#12 #1
  pom.xml
  src/main/java/ru/skypro/homework/HomeworkApplication.java
Labels: улучшение

#13 add dto
  src/main/java/ru/skypro/homework/dto/Comment.java
  src/main/java/ru/skypro/homework/dto/CreateOrUpdateComment.java
  src/main/java/ru/skypro/homework/dto/NewPassword.java
  src/main/java/ru/skypro/homework/dto/UpdateUser.java
Labels: улучшение

#14 add dto
  src/main/java/ru/skypro/homework/dto/Ad.java
  src/main/java/ru/skypro/homework/dto/Ads.java
  src/main/java/ru/skypro/homework/dto/CreateOrUpdateAd.java
  src/main/java/ru/skypro/homework/dto/ExtendedAd.java
Labels: улучшение

#19 Add dto
  src/main/java/ru/skypro/homework/dto/Comments.java
  src/main/java/ru/skypro/homework/dto/User.java
Labels: улучшение

#20 Add dto
  src/main/java/ru/skypro/homework/dto/Comments.java
  src/main/java/ru/skypro/homework/dto/User.java
Labels: улучшение

#21 #15-create_controller
  src/main/java/ru/skypro/homework/controller/UserController.java
Labels: улучшение

#18 #17
  src/main/java/ru/skypro/homework/controller/CommentController.java
Labels: улучшение

#22 #15
  src/main/java/ru/skypro/homework/controller/UserController.java
Labels: улучшение

#23 #16
  src/main/java/ru/skypro/homework/controller/AdController.java
Labels: улучшение

#26 #25
  .github/workflows/javadoc.yml
Labels: документация

#27 Feature/controllers
  .github/workflows/javadoc.yml
  src/main/java/ru/skypro/homework/controller/AdController.java
  src/main/java/ru/skypro/homework/controller/CommentController.java
  src/main/java/ru/skypro/homework/controller/UserController.java
Labels: улучшение

#29 #28
  src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
  src/main/java/ru/skypro/homework/controller/AdController.java
  src/main/java/ru/skypro/homework/controller/AuthController.java
  src/main/java/ru/skypro/homework/controller/CommentController.java
  src/main/java/ru/skypro/homework/controller/UserController.java
  src/main/java/ru/skypro/homework/dto/CreateOrUpdateComment.java
  src/main/java/ru/skypro/homework/dto/ad/Ad.java
  src/main/java/ru/skypro/homework/dto/ad/Ads.java
  src/main/java/ru/skypro/homework/dto/ad/CreateOrUpdateAd.java
  src/main/java/ru/skypro/homework/dto/ad/ExtendedAd.java
  src/main/java/ru/skypro/homework/dto/comment/Comment.java
  src/main/java/ru/skypro/homework/dto/comment/Comments.java
  src/main/java/ru/skypro/homework/dto/comment/CreateOrUpdateComment.java
  src/main/java/ru/skypro/homework/dto/user/Login.java
  src/main/java/ru/skypro/homework/dto/user/NewPassword.java
  src/main/java/ru/skypro/homework/dto/user/Register.java
  src/main/java/ru/skypro/homework/dto/user/Role.java
  src/main/java/ru/skypro/homework/dto/user/UpdateUser.java
  src/main/java/ru/skypro/homework/dto/user/User.java
  src/main/java/ru/skypro/homework/service/AuthService.java
  src/main/java/ru/skypro/homework/service/impl/AuthServiceImpl.java
Labels: улучшение

#32 # 31
  pom.xml
  src/main/resources/application.properties
Labels: исправление

#44 # 37
  src/main/resources/application.properties
Labels: улучшение

#55 #54
  src/main/java/ru/skypro/homework/exception/IllegalDataException.java
  src/main/java/ru/skypro/homework/validate/DataValidator.java
Labels: улучшение

#56 #54-data_validation
  src/main/java/ru/skypro/homework/component/DataValidator.java
  src/main/java/ru/skypro/homework/component/Validatable.java
  src/main/java/ru/skypro/homework/validate/DataValidator.java
Labels: улучшение

#50 # 37
  pom.xml
  src/main/resources/application.properties
  src/main/resources/liquibase/changelog-master.yml
  src/main/resources/liquibase/script/db-schema.sql
Labels: улучшение

#52 #38
  .gitignore
  src/main/java/ru/skypro/homework/repository/AdRepository.java
Labels: улучшение

#47 #36
  src/main/java/ru/skypro/homework/model/CommentEntity.java
  src/main/java/ru/skypro/homework/validate/DataValidator.java
Labels: улучшение

#48 #39
  .gitignore
  pom.xml
  src/main/java/ru/skypro/homework/dto/comment/CommentEntity.java
  src/main/java/ru/skypro/homework/repository/CommentRepository.java
  src/main/resources/application-dev.properties
Labels: улучшение
